name: 💎 Enhancement Bounty
description: "Propose a new feature, service, or improvement with an attached bounty."
title: "[Enhancement]: "
labels: ["✨ Enhancement", "🔍 Triage"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > **This issue template is exclusively for proposing new features, services, or improvements with an attached bounty.** Enhancements without a bounty can be discussed in the appropriate category of [Github Discussions](https://github.com/coollabsio/coolify/discussions).

        # 💎 Add a Bounty (with [algora.io](https://console.algora.io/org/coollabsio/bounties/new))
          - [Click here to add the required bounty](https://console.algora.io/org/coollabsio/bounties/new)

  - type: dropdown
    attributes:
      label: Request Type
      description: Select the type of request you are making.
      options:
        - New Feature
        - New Service
        - Improvement
        - Bug Fix
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the feature, improvement, or service you are proposing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Requirements / How It Should Work
      description: Describe in detail how the feature, service, or improvement should function. Include user flow, expected behavior, or technical implementation notes if applicable.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Criteria to Satisfy Bounty
      description: Define the conditions that must be met for the PR or contribution to be considered complete and eligible for the bounty. Be specific about functionality, tests, or documentation requirements.
      value: |
        1.
        2.
        3.
    validations:
      required: true